name: sentiangreeks_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  flutter_staggered_animations: ^1.1.1
  http: ^1.3.0
  equatable: ^2.0.5
  shimmer: ^3.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  crypto: ^3.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: Inter_18pt-Regular
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf

    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Roboto_Condensed-Regular
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf

    - family: Lobster-Regular
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
